Repository owncloud/richdocuments, pull requests merged in 2018-12, with the labels that each got.

#240 Bump max-version to 10 for semver
  appinfo/info.xml
Labels: 3 - To Review, QA-team

#239 Delete .travis.yml
  .travis.yml
Labels: 4 - To Release, Drone, QA-team

#241 Standardize makefiles and add phan, phpstan
  .drone.yml
  .gitignore
  .phan/config.php
  Makefile
  admin.php
  composer.json
  composer.lock
  lib/AppConfig.php
  lib/AppInfo/Application.php
  lib/Controller/DocumentController.php
  lib/Controller/SettingsController.php
  lib/Db.php
  lib/Db/Storage.php
  lib/Db/Wopi.php
  lib/Helper.php
  lib/HookHandler.php
  lib/Http/DownloadResponse.php
  lib/Http/ResponseException.php
  lib/Storage.php
  phpstan.neon
  templates/admin.php
  templates/documents.php
  templates/public.php
  tests/unit/AppInfo/ApplicationTest.php
  tests/unit/Controller/DocumentControllerTest.php
  vendor-bin/phan/composer.json
  vendor-bin/phpstan/composer.json
Labels: 3 - To Review, Drone, QA-team
