Repository owncloud/richdocuments, pull requests merged in 2020-12, with the labels that each got.

#365 Minor bugfixes
  README.md
  js/viewer/viewer.js
  lib/AppConfig.php
  lib/Controller/DocumentController.php
  templates/admin.php
Labels: 3 - To Review

#373 [Tests-Only][CI] fix the starlark code for reduced ci after merge and sonarcloud
  .drone.star
  .gitignore
  sonar-project.properties
Labels: QA-team

#376 [tests-only] Implement latest .drone.star as at 2020-12-22
  .drone.star
  vendor-bin/behat/composer.json
  vendor-bin/php_codesniffer/composer.json
Labels: 3 - To Review, QA-team
