Repository owncloud/richdocuments, pull requests merged in 2020-03, with the labels that each got.

#323 Revert "do not run acceptance tests against 'latest' 10.3.2 server"
  .drone.star
Labels: 4 - To Release, Drone, QA-team

#326 Exclude drone.star from release tarball
  Makefile
Labels: 4 - To Release, QA-team

#328 Pin behat/mink to 1.7.1 and update other acceptance test dependencies
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#329 A global config switch to (not) open in a new tab
  js/viewer/viewer.js
  lib/AppConfig.php
  lib/AppInfo/Application.php
  lib/HookHandler.php
  tests/unit/AppConfigTest.php
  tests/unit/AppInfo/ApplicationTest.php
Labels: 3 - To Review

#330 add a background job for deleting expired tokens
  appinfo/info.xml
  lib/BackgroundJob/CleanupExpiredWopiTokens.php
  lib/Controller/DocumentController.php
  lib/Db/Wopi.php
  tests/unit/BackgroundJob/CleanupExpiredWopiTokensTest.php
Labels: 3 - To Review

#327 Remove header's buttons when the file is accessed through public link
  lib/Controller/DocumentController.php
  templates/documents.php
Labels: 3 - To Review
